apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-deployer-binding
subjects:
- kind: User
  name: rajinie-github-deployment@dev-ops-475910.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: github-deployer-role
  apiGroup: rbac.authorization.k8s.io